# File: .github/workflows/template-sync.yml

on:
  schedule:
    - cron:  "*/15 * * * *"
  jobs:
    repo-sync:
      runs-on: ubuntu-latest
  
      steps:
        # To use this repository's private action, you must check out the repository
        - name: Checkout
          uses: actions/checkout@v2
        - name: actions-template-sync
          uses: actions/actions-template-sync
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            source_repo_path: stabacco/python-template