name: Update Data

on:
  pull_request:
  push:
    branches: [master]
jobs:
  update-data:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.4
      - name: Update data
        run: poetry run python financialdata/download.py
      - name: Commit updated data
        uses: zwaldowski/git-commit-action@v1
      - run: echo "Updated data ${{ steps.git_commit.outputs.sha }}"
